apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheusdemoapp
  labels:
    release: prometheusdemoapp
spec:
  selector:
    matchLabels:
      app: prometheusdemoapp
  endpoints:
  - port: metrics
