apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheusdemoapp
  labels:
    app: prometheusdemoapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: prometheusdemoapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: 8000
      labels:
        app: prometheusdemoapp
    spec:
      containers:
      - name: prometheusdemoapp
        image: ACR_ENDPOINT/prometheusdemoapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
